apiVersion: v1
kind: Service
metadata:
  name: {{ template "mychart.name" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.internalPort }}
    name: {{ .Values.service.name }}
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}