apiVersion: v1
kind: Service
metadata:
  name: {{ template "mqttclient.name" . }}
  labels:
    {{- include "mqttclient.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mqttclient.service.type }}
  ports:
  - port: {{ .Values.mqttclient.service.internalPort }}
    name: {{ .Values.mqttclient.service.name }}
  selector:
    {{- include "mqttclient.selectorLabels" . | nindent 4 }}