# the image properties get overwritten by the IKS toolchain
image:
  repository: vernemq/vernemq
  tag: 1.12.3
  # pullSecret: all-icr-io
  pullPolicy: IfNotPresent
  # for local development against Minikube registry
  #pullPolicy: Never  
service:
  type: ClusterIP
  epmd:
    port: 4369
    name: epmd
  vmq:
    port: 44053
    name: vmq
  httpDashboard:
    port: 8888
    name: http-dashboard
  tcpMqtt:
    port: 1883
    name: tcp-mqtt
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
