apiVersion: v1
kind: Service
metadata:
  name: {{ template "mychart.name" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.epmd.port }}
    name: {{ .Values.service.epmd.name }}
  - port: {{ .Values.service.vmq.port }}
    name: {{ .Values.service.vmq.name }}
  - port: {{ .Values.service.httpDashboard.port }}
    name: {{ .Values.service.httpDashboard.name }}
  - port: {{ .Values.service.tcpMqtt.port }}
    name: {{ .Values.service.tcpMqtt.name }}
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}